"""Canonical list of Lowe's store metadata for Florida (Stuart to Miami region)."""

from __future__ import annotations

LOWES_STORES_FL: dict[str, dict[str, str]] = {
    # --- MARTIN COUNTY ---
    "1109": {
        "name": "LOWE'S OF STUART, FL",
        "address": "Stuart, FL",
        "city": "Stuart",
        "state": "FL",
        "zip": "34994",
        "url": "https://www.lowes.com/store/FL-Stuart/1109",
    },
    # --- PALM BEACH COUNTY ---
    "1962": {
        "name": "LOWE'S OF WEST PALM BEACH, FL",
        "address": "West Palm Beach, FL",
        "city": "West Palm Beach",
        "state": "FL",
        "zip": "33409",
        "url": "https://www.lowes.com/store/FL-West-Palm-Beach/1962",
    },
    "1720": {
        "name": "LOWE'S OF LAKE PARK, FL",
        "address": "Lake Park, FL",
        "city": "Lake Park",
        "state": "FL",
        "zip": "33403",
        "url": "https://www.lowes.com/store/FL-Lake-Park/1720",
    },
    "0654": {
        "name": "LOWE'S OF ROYAL PALM BEACH, FL",
        "address": "Royal Palm Beach, FL",
        "city": "Royal Palm Beach",
        "state": "FL",
        "zip": "33411",
        "url": "https://www.lowes.com/store/FL-Royal-Palm-Beach/0654",
    },
    "1111": {
        "name": "LOWE'S OF BOYNTON BEACH, FL",
        "address": "Boynton Beach, FL",
        "city": "Boynton Beach",
        "state": "FL",
        "zip": "33426",
        "url": "https://www.lowes.com/store/FL-Boynton-Beach/1111",
    },
    "1069": {
        "name": "LOWE'S OF BOCA RATON, FL",
        "address": "Boca Raton, FL",
        "city": "Boca Raton",
        "state": "FL",
        "zip": "33428",
        "url": "https://www.lowes.com/store/FL-Boca-Raton/1069",
    },
    # --- BROWARD COUNTY ---
    "1792": {
        "name": "LOWE'S OF POMPANO BEACH, FL",
        "address": "Pompano Beach, FL",
        "city": "Pompano Beach",
        "state": "FL",
        "zip": "33069",
        "url": "https://www.lowes.com/store/FL-Pompano-Beach/1792",
    },
    "0704": {
        "name": "LOWE'S OF CORAL SPRINGS, FL",
        "address": "Coral Springs, FL",
        "city": "Coral Springs",
        "state": "FL",
        "zip": "33065",
        "url": "https://www.lowes.com/store/FL-Coral-Springs/0704",
    },
    "0754": {
        "name": "LOWE'S OF OAKLAND PARK, FL",
        "address": "Oakland Park, FL",
        "city": "Oakland Park",
        "state": "FL",
        "zip": "33334",
        "url": "https://www.lowes.com/store/FL-Oakland-Park/0754",
    },
    "1113": {
        "name": "LOWE'S OF SUNRISE, FL",
        "address": "Sunrise, FL",
        "city": "Sunrise",
        "state": "FL",
        "zip": "33323",
        "url": "https://www.lowes.com/store/FL-Sunrise/1113",
    },
    "1681": {
        "name": "LOWE'S OF PEMBROKE PINES, FL",
        "address": "Pembroke Pines, FL",
        "city": "Pembroke Pines",
        "state": "FL",
        "zip": "33027",
        "url": "https://www.lowes.com/store/FL-Pembroke-Pines/1681",
    },
    "0725": {
        "name": "LOWE'S OF SOUTHWEST RANCHES, FL",
        "address": "Southwest Ranches, FL",
        "city": "Southwest Ranches",
        "state": "FL",
        "zip": "33331",
        "url": "https://www.lowes.com/store/FL-Southwest-Ranches/0725",
    },
    "3315": {
        "name": "LOWE'S OF DAVIE, FL",
        "address": "Davie, FL",
        "city": "Davie",
        "state": "FL",
        "zip": "33324",
        "url": "https://www.lowes.com/store/FL-Davie/3315",
    },
    # --- MIAMI-DADE COUNTY ---
    "1841": {
        "name": "LOWE'S OF HIALEAH (N.W. MIAMI-DADE), FL",
        "address": "Hialeah, FL",
        "city": "Hialeah",
        "state": "FL",
        "zip": "33016",
        "url": "https://www.lowes.com/store/FL-Hialeah/1841",
    },
    "2254": {
        "name": "LOWE'S OF HIALEAH, FL",
        "address": "Hialeah, FL",
        "city": "Hialeah",
        "state": "FL",
        "zip": "33012",
        "url": "https://www.lowes.com/store/FL-Hialeah/2254",
    },
    "3413": {
        "name": "LOWE'S OF NORTH MIAMI BEACH, FL",
        "address": "North Miami Beach, FL",
        "city": "North Miami Beach",
        "state": "FL",
        "zip": "33162",
        "url": "https://www.lowes.com/store/FL-N.-Miami-Beach/3413",
    },
    "2904": {
        "name": "LOWE'S OF MIAMI (KENDALL), FL",
        "address": "Miami, FL",
        "city": "Miami",
        "state": "FL",
        "zip": "33186",
        "url": "https://www.lowes.com/store/FL-Miami/2904",
    },
    "2707": {
        "name": "LOWE'S OF HOMESTEAD, FL",
        "address": "Homestead, FL",
        "city": "Homestead",
        "state": "FL",
        "zip": "33033",
        "url": "https://www.lowes.com/store/FL-Homestead/2707",
    },
}
